### ISSUE TITLE
Node got strucked and Syncing is not happening

### ISSUE THREAD

**Issue by sowjanya-vangeti** [smartcontracts/simple-optimism-node#158]
I was trying to sync op-sepolia testnet ,till this block count it got synced (14,966,437).After that syncing is not happening

These are my logs:

![image](https://github.com/user-attachments/assets/7525096a-13dc-4889-958d-e730783eaa42)

![image](https://github.com/user-attachments/assets/06b3c086-82d7-46e7-b46f-7eabfc4b2d54)

**Comment by Chomtana** [comment]
Possibly relate to this one https://github.com/ethereum-optimism/optimism/issues/8784

It say force shutting down geth causing data to be corrupted

**Comment by sowjanya-vangeti** [comment]
How to resolve this "Unclean shutdown detected" ,I couldn't see data to be corrupted
we are using dockerized method to sync
can you send me the steps or refer document to resolve this issue 

I think it is not out of memory issue.
![image](https://github.com/user-attachments/assets/0159da53-9ff3-48fc-83c5-3c7d101eac5c)

**Comment by Chomtana** [comment]
Seem like resync is the only solution. Shouldn't take more than 1 day for snap sync.

Geth may eat up all RAM in 2 weeks due to memory leak. You may need to increase RAM quite a bit or implement a crontab to automatically restart docker compose every day to prevent this from happening in the future.

### Step 1: Edit the Crontab

Open the crontab file for editing:

```bash
crontab -e
```

### Step 2: Add the Cron Job

Add a line to specify the schedule for restarting your Docker Compose services. You need to specify absolute path to docker-compose.yml

```bash
0 0 * * * docker compose -f .../simple-optimism-node/docker-compose.yml restart
```

**Comment by sowjanya-vangeti** [comment]
Thank you for providing the steps,we will resync from scratch
