### ISSUE TITLE
Syncing from L1 takes weeks

### ISSUE THREAD

**Issue by tappikone** [smartcontracts/simple-optimism-node#24]
Syncing from L1 is too slow. Syncing from L2 is the default method for official node quide.

Also using snapshots makes l2geth crash.

Suggesting to change the default method to sync from L2.

**Comment by smartcontracts** [comment]
Syncing from L1 takes a few days but shouldn't take weeks. Are you using a network volume by any chance? I highly recommend using a machine with a dedicated SSD instead of a network volume. I can add L2 sync as an option though.

**Comment by smartcontracts** [comment]
Working on L2 sync here #26

**Comment by tappikone** [comment]
> Syncing from L1 takes a few days but shouldn't take weeks. Are you using a network volume by any chance? I highly recommend using a machine with a dedicated SSD instead of a network volume. I can add L2 sync as an option though.

It may very well be some weird problem in my end but can't figure out what. Running local server with SSD, 1gbit fiber and plenty of resources to spare. Also the speed of syncing stays stable and the "blocks left to sync" decreases. No errors.

I now got dtl synced with L2 but again l2geth crashes instantly when it gets a connection to dtl. I've tried fresh install 20 times now.

**Comment by smartcontracts** [comment]
Hmmm... can I see your environment variables? (with sensitive info removed)

**Comment by tappikone** [comment]
I don't think there's anything interesting. Just filled the three with alchemy nodes. Could be faster if I ran my own L1 node?

**Comment by smartcontracts** [comment]
Usually memory and disk times on the L2 side are the bottleneck. You might be able to speed things up by allocating more RAM to the geth cache. Just add `--cache=16384 \` (or however much memory you want to allocate in MB) to `l2geth-start.sh`.

**Comment by smartcontracts** [comment]
If you're syncing from L2, make sure you set `ROLLUP_BACKEND=l1` in your Geth environment

**Comment by smartcontracts** [comment]
Closing, not much I can do here beyond the notes listed above

**Comment by 0xpanoramix** [comment]
Hi @smartcontracts ! I'm re-opening this issue because I'm facing the same crash with l2geth when using snapshots (which I got from the link posted in #42).

To be exact, the segfault happens at [this line](https://github.com/ethereum-optimism/optimism/blob/0f1692afe0b9cf7afc681615a7ce6817bfd94c7e/l2geth/rollup/sync_service.go#L291).

Any ideas on this ? I don't know the entire codebase of l2geth but I suppose it's either `GetRawTransaction` which returns a nil transaction or the inner `Transaction` object which is nil.

What would be your guess ?
